"""Pure authoring helpers: world-file / script / PROTO / CSV generation and
lighting presets. No Webots (`controller`) imports, so unit-testable standalone.

Used by the bridge (script export, proto extraction, record CSV) and the server
(world templates, backups). All emit plain text / plain data.
"""

import re

WEBOTS_HEADER = "#VRML_SIM R2025a utf8"


# ---------------------------------------------------------------------------
# World templates (8.6)
# ---------------------------------------------------------------------------

LIGHTING_PRESETS = {
    "indoor": {"sky": [0.6, 0.62, 0.65],
               "lights": [{"type": "DirectionalLight", "direction": [-0.5, -0.5, -1],
                           "intensity": 2.0, "castShadows": True}]},
    "outdoor": {"sky": [0.4, 0.6, 0.9],
                "lights": [{"type": "DirectionalLight", "direction": [1, -1, -3],
                            "intensity": 3.5, "castShadows": True}]},
    "studio": {"sky": [0.9, 0.9, 0.9],
               "lights": [{"type": "DirectionalLight", "direction": [-1, -0.5, -1],
                           "intensity": 2.5, "castShadows": False},
                          {"type": "DirectionalLight", "direction": [1, 0.5, -1],
                           "intensity": 1.5, "castShadows": False}]},
    "night": {"sky": [0.02, 0.02, 0.05],
              "lights": [{"type": "DirectionalLight", "direction": [-0.3, -0.3, -1],
                          "intensity": 0.4, "castShadows": True}]},
}


def lighting_preset(preset):
    if preset not in LIGHTING_PRESETS:
        raise ValueError(f"unknown lighting preset {preset!r}; "
                         f"choose from {sorted(LIGHTING_PRESETS)}")
    return LIGHTING_PRESETS[preset]


def _light_node(spec, intensity=None):
    it = intensity if intensity is not None else spec.get("intensity", 1.0)
    d = spec.get("direction", [0, 0, -1])
    return (f'DirectionalLight {{ direction {d[0]} {d[1]} {d[2]} '
            f'intensity {it} castShadows {"TRUE" if spec.get("castShadows") else "FALSE"} }}')


def world_template_wbt(name="world", template="empty", size=10.0,
                       coordinate_system="ENU", lighting="indoor"):
    """Generate a valid R2025a .wbt using base nodes only (no EXTERNPROTO needed).
    Templates: 'empty' (floor only), 'indoor_room' (floor + 4 walls),
    'outdoor_flat' (large floor)."""
    if template not in ("empty", "indoor_room", "outdoor_flat"):
        raise ValueError(f"unknown template {template!r}")
    half = size / 2.0
    preset = lighting_preset(lighting)
    sky = preset["sky"]
    lines = [WEBOTS_HEADER,
             f"WorldInfo {{ coordinateSystem \"{coordinate_system}\" basicTimeStep 32 }}",
             f"Viewpoint {{ position {size} {-size} {size * 0.8} "
             f"orientation 0.3 0.3 0.88 2.0 }}",
             f"Background {{ skyColor [ {sky[0]} {sky[1]} {sky[2]} ] }}"]
    for spec in preset["lights"]:
        lines.append(_light_node(spec))
    floor_size = size * 2 if template == "outdoor_flat" else size
    lines.append(
        f'DEF FLOOR Solid {{ translation 0 0 0 children [ '
        f'Shape {{ appearance PBRAppearance {{ baseColor 0.8 0.8 0.8 roughness 1 }} '
        f'geometry DEF FLOOR_GEO Plane {{ size {floor_size} {floor_size} }} }} ] '
        f'boundingObject USE FLOOR_GEO name "floor" }}')
    if template == "indoor_room":
        wall_h = 2.0
        t = 0.1
        walls = [(0, half, [size, t, wall_h]), (0, -half, [size, t, wall_h]),
                 (half, 0, [t, size, wall_h]), (-half, 0, [t, size, wall_h])]
        for i, (x, y, dim) in enumerate(walls):
            lines.append(
                f'DEF WALL_{i} Solid {{ translation {x} {y} {wall_h / 2} children [ '
                f'Shape {{ appearance PBRAppearance {{ baseColor 0.9 0.9 0.85 }} '
                f'geometry DEF WG_{i} Box {{ size {dim[0]} {dim[1]} {dim[2]} }} }} ] '
                f'boundingObject USE WG_{i} name "wall_{i}" }}')
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Script / scenario export (10.1)
# ---------------------------------------------------------------------------

def python_script_from_nodes(node_strings, header_comment=""):
    """A standalone Supervisor controller that rebuilds the given nodes via
    importMFNodeFromString on the scene root."""
    body = ['"""Auto-generated by webotMCP generate_world_script.',
            header_comment, '"""',
            "from controller import Supervisor",
            "",
            "sup = Supervisor()",
            "root = sup.getRoot().getField('children')",
            "",
            "NODES = ["]
    for s in node_strings:
        body.append("    " + repr(s) + ",")
    body += ["]", "",
             "for node_string in NODES:",
             "    root.importMFNodeFromString(-1, node_string)",
             "",
             "timestep = int(sup.getBasicTimeStep())",
             "while sup.step(timestep) != -1:",
             "    pass"]
    return "\n".join(body) + "\n"


def json_scenario_from_objects(objects, physics=None, conditions=None,
                               duration_s=None):
    """Declarative scenario dict: object list (+ optional node_string), physics,
    success/failure conditions, duration."""
    scenario = {"version": 1, "objects": objects}
    if physics:
        scenario["physics"] = physics
    if conditions:
        scenario["conditions"] = conditions
    if duration_s is not None:
        scenario["duration_s"] = duration_s
    return scenario


# ---------------------------------------------------------------------------
# PROTO authoring (8.7)
# ---------------------------------------------------------------------------

_SF_FIELD_TYPES = {"translation": "SFVec3f", "rotation": "SFRotation",
                   "name": "SFString"}
_DEFAULTS = {"translation": "0 0 0", "rotation": "0 0 1 0", "name": '"solid"'}


def wrap_proto(node_string, proto_name, expose=("translation", "rotation", "name")):
    """Wrap an exported node string as a reusable PROTO exposing the listed SF
    fields (translation/rotation/name) as parameters via IS. Returns the .proto
    text. Fields not present in the node are still exposed with sensible
    defaults so the PROTO is always instantiable."""
    if not re.match(r"^[A-Za-z_]\w*$", proto_name):
        raise ValueError("proto_name must be a valid identifier")
    body = node_string.strip()
    # strip a leading DEF so the PROTO body is a bare node
    body = re.sub(r"^DEF\s+\w+\s+", "", body)
    fields = []
    for f in expose:
        ftype = _SF_FIELD_TYPES.get(f)
        if ftype is None:
            continue
        m = re.search(rf"\b{f}\s+([^\n]+?)\s+(?=[A-Za-z]+\s|\]|\}}|$)", body)
        default = _DEFAULTS[f]
        if f == "name":
            mn = re.search(r'\bname\s+"([^"]*)"', body)
            if mn:
                default = f'"{mn.group(1)}"'
        elif m:
            default = m.group(1).strip()
        fields.append(f"  field {ftype} {f} {default}")
        # rewrite occurrences to IS
        if f == "name":
            body = re.sub(r'\bname\s+"[^"]*"', "name IS name", body, count=1)
        else:
            # match the field name + its whitespace-separated numeric values
            # (handles scientific notation like 7.3e-17 without splitting on 'e'
            # and without swallowing the following field/newline).
            num = r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?"
            body = re.sub(rf"\b{f}(?:\s+{num})+",
                          f"{f} IS {f}", body, count=1)
    # ensure the exposed fields exist in the body (inject if missing)
    for f in expose:
        if f in _SF_FIELD_TYPES and f"{f} IS {f}" not in body:
            body = re.sub(r"\{", f"{{ {f} IS {f}", body, count=1)
    header = [WEBOTS_HEADER, f"PROTO {proto_name} ["] + fields + ["]", "{", body, "}"]
    return "\n".join(header) + "\n"


# ---------------------------------------------------------------------------
# Time-series CSV (9.4)
# ---------------------------------------------------------------------------

def records_to_csv(rows, columns):
    """rows: list of dicts; columns: ordered list of keys. Returns CSV text."""
    out = [",".join(columns)]
    for r in rows:
        out.append(",".join(_csv_cell(r.get(c, "")) for c in columns))
    return "\n".join(out) + "\n"


def _csv_cell(v):
    if isinstance(v, (list, tuple)):
        v = " ".join(str(x) for x in v)
    s = str(v)
    if "," in s or '"' in s or "\n" in s:
        return '"' + s.replace('"', '""') + '"'
    return s


def cad_shape_node_string(url, name="cad", physics=False, bounding_box=None,
                          position=(0, 0, 0)):
    """A Solid wrapping a CadShape that renders an .obj/.dae mesh. Optional axis-
    aligned Box boundingObject ([x,y,z]) and Physics for a dynamic object."""
    x, y, z = position
    # VRML strings treat '\' as an escape; use forward slashes so Windows paths
    # (C:\Users\...) don't corrupt the url ("Invalid escaped character").
    url = str(url).replace("\\", "/")
    parts = [f'Solid {{ translation {x} {y} {z} name "{name}" '
             f'children [ CadShape {{ url [ "{url}" ] }} ]']
    if bounding_box:
        b = bounding_box
        parts.append(f'boundingObject Box {{ size {b[0]} {b[1]} {b[2]} }}')
    if physics:
        parts.append("physics Physics { }")
    parts.append("}")
    return " ".join(parts)


def supervisor_script_scaffold(name, code=""):
    """A standalone Supervisor controller with robust node/field helpers matching
    the bridge, ready to run at full speed as an extern controller."""
    return (f'"""Supervisor automation script \'{name}\' (webotMCP scaffold)."""\n'
            "from controller import Supervisor, Field\n\n"
            "sup = Supervisor()\n"
            "timestep = int(sup.getBasicTimeStep())\n\n"
            "def node(ref):\n"
            "    n = sup.getFromDef(ref)\n"
            "    if n is None:\n"
            "        try:\n"
            "            n = sup.getFromId(int(ref))\n"
            "        except (TypeError, ValueError):\n"
            "            n = None\n"
            "    if n is None:\n"
            "        raise ValueError('node not found: %r' % (ref,))\n"
            "    return n\n\n"
            "def field(ref, name):\n"
            "    return node(ref).getField(name)\n\n"
            "# ---- user code ----\n"
            f"{code}\n")


def extern_controller_command(exe, controller_path, robot=None, protocol=None,
                              port=None, extra_args=None):
    """Build the webots-controller launcher argv. Only includes flags that are
    provided (robot-name, protocol, port). A .py controller is passed directly so
    webots-controller wires up PYTHONPATH and runs it with the system Python."""
    cmd = [str(exe)]
    if robot:
        cmd.append(f"--robot-name={robot}")
    if protocol:
        cmd.append(f"--protocol={protocol}")
    if port:
        cmd.append(f"--port={port}")
    cmd.append(str(controller_path))
    if extra_args:
        cmd.extend(str(a) for a in extra_args)
    return cmd


def summarize_series(rows, value_key):
    """min/max/mean of a numeric column across rows (ignoring missing)."""
    vals = [r[value_key] for r in rows if isinstance(r.get(value_key), (int, float))]
    if not vals:
        return None
    return {"min": round(min(vals), 5), "max": round(max(vals), 5),
            "mean": round(sum(vals) / len(vals), 5), "count": len(vals)}
